import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import "./globals.css";
import { NavMenu } from "@/components/global/navmenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <div className="flex justify-between sticky top-0 items-center p-2 px-4 h-16 bg-red-100 border-b border-border">
            <h1 className="text-2xl font-bold text-zinc-800">PetConnect</h1>
            <SignedOut>
              <SignInButton>Get Started</SignInButton>
            </SignedOut>
            <SignedIn>
              <NavMenu />
            </SignedIn>
          </div>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
